package com.example.data.model

import androidx.room.Entity
import androidx.room.PrimaryKey

// --- DATABASE ENTITIES ---

@Entity(tableName = "saved_cities")
data class SavedCity(
    @PrimaryKey val name: String,
    val temp: Double,
    val condition: String,
    val isFavorite: Boolean = false,
    val timestamp: Long = System.currentTimeMillis()
)

@Entity(tableName = "severe_alerts")
data class SavedAlert(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val cityName: String,
    val title: String,
    val description: String,
    val severity: String, // "Moderate", "Severe", "Extreme"
    val time: Long = System.currentTimeMillis(),
    val isRead: Boolean = false
)

// --- WEATHER PRESENTATION MODELS ---

data class WeatherReport(
    val cityName: String,
    val temperature: Double,
    val condition: String,
    val highTemp: Double,
    val lowTemp: Double,
    val humidityPercent: Int,
    val windSpeedMph: Double,
    val windDirection: String,
    val uvIndex: Int,
    val pressureMb: Int,
    val visibilityMiles: Double,
    val isAlertActive: Boolean,
    val activeAlertTitle: String?,
    val activeAlertDesc: String?,
    val runSuitabilityScore: Int, // 1 to 10
    val runSuitabilityText: String, // e.g. "Perfect for a light jog"
    val hourlyForecast: List<HourlyForecast>,
    val dailyForecast: List<DailyForecast>,
    val aiInsight: String? = null // Generated by Gemini AI Weather Insights
) {
    val feelsLike: Double
        get() {
            return if (temperature >= 80.0) {
                // Heat Index simplified approximation
                temperature + 0.5 * (temperature - 70.0 + (humidityPercent - 50.0) / 10.0)
            } else if (temperature <= 50.0) {
                // Wind Chill simplified approximation
                35.74 + 0.6215 * temperature - 35.75 * Math.pow(windSpeedMph, 0.16) + 0.4275 * temperature * Math.pow(windSpeedMph, 0.16)
            } else {
                // Mild temperature adjustment
                temperature + (humidityPercent - 50.0) / 10.0 - (windSpeedMph / 5.0)
            }
        }
}

data class HourlyForecast(
    val timeLabel: String, // e.g., "12 PM"
    val temp: Double,
    val condition: String,
    val precipitationChance: Int, // e.g. 40 for 40%
    val windSpeedMph: Double
)

data class DailyForecast(
    val dayLabel: String, // e.g., "Monday"
    val condition: String,
    val lowTemp: Double,
    val highTemp: Double,
    val precipitationChance: Int // e.g. 60 for 60%
)
